/*
This file contains all constants in the app.
*/

const C = {
    // ACTION TYPES

    //TIMER
    TIMER_SET: 'TIMER_SET',
    TIMER_START: 'TIMER_START',
    TIMER_STOP: 'TIMER_STOP',
    TIMER_TICK: 'TIMER_TICK',

    //STOPWATCH
    STOPWATCH_RESET: 'STOPWATCH_RESET',
    STOPWATCH_START: 'STOPWATCH_START',
    STOPWATCH_STOP: 'STOPWATCH_STOP',
    STOPWATCH_TICK: 'STOPWATCH_TICK'
};

export default C;
