/*
This file contains all constants in the app.
*/

const C = {
    // ACTION TYPES
    AIM_AT: 'AIM_AT',
    BOMB_AT: 'BOMB_AT',
    KILL_HERO: 'KILL_HERO',
    RESET: 'RESET',
    UNLOCK_KEYPAD: 'UNLOCK_KEYPAD',
    ENTER_LAUNCH_CODES: 'ENTER_LAUNCH_CODES',
    LAUNCH_MISSILES: 'LAUNCH_MISSILES',
    TOTAL_ANNIHILATION: 'TOTAL_ANNIHILATION',
    TAKE_NUKE_STEP: 'TAKE_NUKE_STEP',
    DUCK_DOWN: 'DUCK_DOWN',
    STAND_UP: 'STAND_UP',
    END_BOMB: 'END_BOMB',

    // HERO STATUSES
    AIMING: 'AIMING',
    DUCKING: 'DUCKING',
    UNLOCKING_KEYPAD: 'UNLOCKING_KEYPAD',
    ENTERING_LAUNCH_CODES: 'ENTERING_LAUNCH_CODES',
    ENDS_THE_WORLD: 'ENDS_THE_WORLD',
    BOMBING: 'BOMBING',
    WAITING: 'WAITING',
    DEAD: 'DEAD'
};

export default C;
